### ISSUE TITLE
Tracking issue for failure 0.1.1

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/failure#80]
Hoping to release some time this week.

- [x] Merge #54 (Causes Iterator)
- [x] Merge #74 (bail! and ensure!)
- [x] Expose derive from failure directly (#71)
- [x] Make derive no_std compatible.
- [x] Add `From<D> for Context<D>` (#75)
- [x] Add a change log or release notes or something
- [x] Make a blog post
